version: '2'

services:
  prometheus:
    build: .
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - cxf-network
    depends_on:
      - cxf

  grafana:
    image: grafana/grafana
    expose:
      - 3000    
    ports:
      - 3000:3000
    networks:
      - cxf-network
    depends_on:
      - prometheus

  cxf:
    image: jax-rs-2.0-cxf-metrics:latest
    expose:
    - 19090
    - 9323
    ports:
      - 19090:19090
      - 9323:9323
    networks:
      - cxf-network
      
  jaeger:
    image: jaegertracing/all-in-one:latest
    expose:
      - 5775
      - 6831
      - 6832
      - 5778
      - 16686
      - 14268
      - 9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    networks:
      - cxf-network
    depends_on:
      - cxf
      
networks:
    cxf-network:
       driver: bridge