version: '2'

services:
  prometheus:
    build: .
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - cxf-network
    depends_on:
      - cxf

  grafana:
    image: grafana/grafana
    expose:
      - 3000    
    ports:
      - 3000:3000
    networks:
      - cxf-network
    depends_on:
      - prometheus

  cxf:
    image: jax-rs-2.0-cxf-metrics:latest
    mem_limit: 256MB
    expose:
    - 19090
    ports:
      - 19090:19090
    networks:
      - cxf-network
      
networks:
    cxf-network:
       driver: bridge