apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: cxf
    name: cxf
  spec:
    replicas: 1 
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: cxf
      spec:
        containers:
        - image: jax-rs-2.0-cxf-metrics:latest
          name: cxf
          ports:
          - containerPort: 19090
          - containerPort: 9323
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: cxf
    name: cxf
  spec:
    ports:
    - name: "19090"
      port: 19090
      targetPort: 19090
    - name: "9323"
      port: 9323
      targetPort: 9323
    selector:
      io.kompose.service: cxf
  status:
    loadBalancer: {}
